[profile.default]
src = "contracts"
out = "out"
test = "tests"
libs = ["lib"]
solc_version = "0.8.20"
remappings = [
    "@openzeppelin/=node_modules/@openzeppelin/",
    "forge-std/=lib/forge-std/src/",
]
