import { Command, Options } from "@effect/cli";
import { BunContext, BunRuntime } from "@effect/platform-bun";
import { Effect, Layer } from "effect";
import * as fs from "node:fs"; import * as path from "node:path";
const version = (() => { try { return JSON.parse(fs.readFileSync(path.join(__dirname, "..", "package.json"), "utf-8")).version || "0.0.0"; } catch { return "0.0.0"; } })();
const runtimeInfo = () => { const rt = typeof Bun !== "undefined" ? "bun" : "node"; const ver = rt === "bun" ? (Bun as any).version : process.version; return "t3code v" + version + " (" + rt + " " + ver + ", " + process.platform + " " + process.arch + ")"; };
const versionFlag = Options.boolean("version").pipe(Options.withAlias("V"));
const versionCmd = Command.make("version", {}, () => Effect.sync(() => { console.log(runtimeInfo()); }));
const rootCmd = Command.make("t3", { version: versionFlag }).pipe(Command.withSubcommands([versionCmd]), Command.withHandler(({ version: showVersion }) => Effect.sync(() => { console.log(runtimeInfo()); })));
Command.run(rootCmd, { name: "t3code", version })(process.argv);