TLSCERT ; TLS certificate helpers with isolated hash side effects
 ;
HASH(RAWCERT,SESSID,CERTID) ;
 N JOBID,SEQNO,HASH,DUMMY
 S JOBID=$J
 S SEQNO=$G(^XTMP("TLSHASH",JOBID,"seqno"),0)+1
 S ^XTMP("TLSHASH",JOBID,"seqno")=SEQNO
 S HASH=$$COMPHASH^TLSHASH(RAWCERT)
 S ^XTMP("TLSHASH",JOBID,SEQNO)=HASH
 S ^XTMP("TLSHASH",JOBID,SEQNO,"ts")=$H
 S DUMMY=$G(^GLBTLS(SESSID,"cert",CERTID))
 Q HASH

